### ISSUE TITLE
Creating moments with invalid offsets will not return minutes

### ISSUE THREAD

**Issue by iamjon** [levynir/mongoose-timezone-offset#1]
If we create a moment object with an invalid offset, when calling for the offset moment will return the value, instead of the value in minutes.
`
const invalid = moment().offset(17);
const offset =  invalid.offset(); // Will return 17

const valid = moment().offset(8.5);
const offset =  valid.offset(); // Will return 510

`

**Comment by levynir** [comment]
Fixed by @iamjon
